# Generated by Django 5.0.6 on 2024-08-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_delete_credit_delete_keyword_delete_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
