# Generated by Django 5.0.6 on 2024-08-23 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='updated_at',
        ),
    ]
